name: Deploy
on:
  push:
    branches:
    - server-&-client

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    
    - name: Copy repository contents
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        port: ${{ secrets.PORT }}
        key: ${{ secrets.SSHKEY }}
        source: "."
        target: "~/maze"

    - name: Build a docker image
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        port: ${{ secrets.PORT }}
        key: ${{ secrets.SSHKEY }}
        script: docker build --tag maze ~/maze

    - name: Kill and remove old docker container
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        port: ${{ secrets.PORT }}
        key: ${{ secrets.SSHKEY }}
        script: docker stop maze 2>/dev/null; docker rm -f maze 2>/dev/null; docker system prune 2>/dev/null

    - name: Start new docker container
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        port: ${{ secrets.PORT }}
        key: ${{ secrets.SSHKEY }}
        script: >
          docker run
          -v /root/logs:/app/logs
          -p ${{ secrets.APP_PORT }}:5002/udp
          -p ${{ secrets.APP_PORT }}:5002
          --name maze -d maze